version: "3.7"
services:
  app:
    build: .
    container_name: tech-challenge-group-57-pagamento-api
    restart: always
    hostname: app
    ports:
      - 8083:8080
    networks:
      - java-service-network
    environment:
      - spring.datasource.url=mongodb://techchallenge:techchallenge@mongodb:27017/local?authSource=admin
    depends_on:
      - mongodb

    volumes:
      - .m2:/root/.m2

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    hostname: mongodb
    restart: always
    networks:
      - java-service-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: techchallenge
      MONGO_INITDB_ROOT_PASSWORD: techchallenge
      MONGO_INITDB_DATABASE: local
    volumes:
      - ./init-mongo-db/init.js:/docker-entrypoint-initdb.d/init-mongo-db/init.js:ro

networks:
  java-service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
