version: "3.7"
services:
  app:
    build: .
    container_name: tech-challenge-group-57-pagamento-api
    restart: always
    ports:
      - 8083:8080
    networks:
      - java-service-network
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    container_name: tech-challenge-group-57-pagamento-mysql
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    networks:
      - java-service-network
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: techchallenge
      MYSQL_PASSWORD: techchallenge
      MYSQL_ROOT_PASSWORD: techchallenge
networks:
  java-service-network:
