spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  application:
    name: tech-challenge-04-pagamento
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      username: techchallenge
      password: techchallenge
      
application:    
  pagamento:
    webhook-url: ${PAGAMENTO_WEBHOOK_URL:http://localhost:8080/tech-challenge-04-pagamento/pagamento/webhook}
    mercadopago-url: ${PAGAMENTO_MERCADOPAGO_URL:http://localhost:8080/tech-challenge-04-pagamento/pagamento/mercadopago}
  pedido:
    update-status-url: ${UPDATE_STATUS_PEDIDO_URL:http://localhost:8084/tech-challenge-04/pedido}
    
info:
  group-id: "br.com.fiap.soat07"
  artifact-id: "tech-challenge-04-pagamento"
  version: "1.0.0"
  java.version: "17.x"
  
server:
  port: 8080
  max-http-request-header-size: 24KB
  servlet:
    context-path: /tech-challenge-04-pagamento
  tomcat:
    max-http-response-header-size: 24KB
    

logging:
  group:
    web: org.springframework.web, org.springframework.core.codec, org.springframework.http, 
    spring: org.springframework.core.env
    servlet: org.springframework.boot.web, org.apache.coyote, org.apache.catalina, org.apache.tomcat
    data:  org.springframework.jdbc.core,  org.springframework.orm.jpa, org.hibernate
    app: br.com.fiap.soat07.clean
  level:
    web: ${LOGGING_LEVEL_WEB:INFO}
    spring: ${LOGGING_LEVEL_SPRING:INFO}
    servlet: ${LOGGING_LEVEL_SERVLET:INFO}
    data: ${LOGGING_LEVEL_DATA:INFO}
    app: ${LOGGING_LEVEL_APP:INFO}   
